### ISSUE TITLE
Version 1.7 doesn't "get" new outages on initialisation

### ISSUE THREAD

**Issue by axkeyz** [axkeyz/water-api#18]
Steps to reproduce
1. docker-compose up with axkeyz/water:v1.7
2. Fails
```2022/08/03 02:11:32 Server is running
2022/08/03 02:11:32 Connected to database
2022/08/03 02:11:32 Cleanup outages failed: dial tcp 172.19.0.2:5432: connect: connection refused
2022/08/03 02:11:32 Outages have been cleaned up.
2022/08/03 02:11:34 Connected to database
2022/08/03 02:11:34 dial tcp 172.19.0.2:5432: connect: connection refused
2022/08/03 02:11:34 Outage list has been updated.
2022/08/03 02:11:36 Received GetOutage request.
2022/08/03 02:11:36 Connected to database
2022/08/03 02:11:36 SELECT outage_id, street, suburb, st_astext(location), start_date, end_date,
        outage_type FROM outage
2022/08/03 02:11:36 dial tcp 172.19.0.2:5432: connect: connection refused
2022/08/03 02:11:36 http: panic serving 172.27.0.2:53468: runtime error: invalid memory address or nil pointer dereference
goroutine 31 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x6e3f80, 0x9a8c50})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
database/sql.(*Rows).close(0x0, {0x0, 0x0})
        /usr/local/go/src/database/sql/sql.go:3267 +0x8e
database/sql.(*Rows).Close(0x120)
        /usr/local/go/src/database/sql/sql.go:3263 +0x1d
panic({0x6e3f80, 0x9a8c50})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
database/sql.(*Rows).Next(0x0)
        /usr/local/go/src/database/sql/sql.go:2944 +0x27
github.com/axkeyz/water-down-again/api.GetOutages({0x7a91a8, 0xc000464000}, 0xc0000e6500)
        /app/api/controller.go:54 +0x525
net/http.HandlerFunc.ServeHTTP(0x7fb05bfb8108, {0x7a91a8, 0xc000464000}, 0xc000100630)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x7a91a8, 0xc000464000}, 0xc00047c390)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/middleware.go:51 +0xaa
net/http.HandlerFunc.ServeHTTP(0xc0000e6400, {0x7a91a8, 0xc000464000}, 0xc00003f9f8)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000156000, {0x7a91a8, 0xc000464000}, 0xc000104900)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc000070f90}, {0x7a91a8, 0xc000464000}, 0xc000104900)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0004df0e0, {0x7aaa60, 0xc000102b40})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8```

**Comment by axkeyz** [comment]
Closed for now
